services:
  frontend-blue:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8086:3000"
    depends_on:
      - backend-blue
    restart: always

  backend-blue:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5002:6060" # Not 5000 or 5001
    env_file:
      - ./server/.env.dev
    volumes:
      - uploads:/app/public/uploads
    restart: always
    # Remove "command" so Dockerfile's CMD is used

  frontend-green:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8087:3000"
    depends_on:
      - backend-green
    restart: always

  backend-green:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5003:6060" # Use 5003 to avoid conflict
    env_file:
      - ./server/.env.dev
    volumes:
      - uploads:/app/public/uploads
    restart: always
    # Remove "command" override

volumes:
  uploads:
