services:
  frontend-blue:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: calendar_frontend_blue
    ports:
      - "8086:3000" # Exposes your React build on host:port 8086
    networks:
      - calendar_network
    depends_on:
      - backend-blue
    restart: always

  backend-blue:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: calendar_backend_blue
    # If you want the server to read from .env.dev
    env_file:
      - ./server/.env.dev
    ports:
      - "5002:6060" # Exposes Express on host:port 5002
    networks:
      - calendar_network
    restart: always

  frontend-green:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: calendar_frontend_green
    ports:
      - "8087:3000" # Exposes your React build on host:port 8087
    networks:
      - calendar_network
    depends_on:
      - backend-green
    restart: always

  backend-green:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: calendar_backend_green
    env_file:
      - ./server/.env.dev
    ports:
      - "5003:6060" # Exposes Express on host:port 5003
    networks:
      - calendar_network
    restart: always

networks:
  calendar_network:
    driver: bridge
