services:
  frontend-blue:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8086:3000"
    networks:
      - calendar-network
    depends_on:
      - backend-blue
    restart: always

  backend-blue:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5002:6060"
    env_file:
      - .env.production
    volumes:
      - uploads:/app/public/uploads
    restart: always
    networks:
      - calendar-network
    command: node /app/index.js

  frontend-green:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8087:3000"
    networks:
      - calendar-network
    depends_on:
      - backend-green
    restart: always

  backend-green:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5003:6060"
    env_file:
      - .env.production
    volumes:
      - uploads:/app/public/uploads
    restart: always
    networks:
      - calendar-network
    command: node /app/index.js

networks:
  calendar-network:
    external: true

volumes:
  uploads:
